version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - PORT=5000
      - MONGO_URI=mongodb+srv://tugba:tugba123@cluster0.mgitzaa.mongodb.net/pfitcode?retryWrites=true&w=majority
      - JWT_SECRET=supergizlisifre123
    restart: always
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"     # AMQP bağlantı noktası (kod bağlantısı)
      - "15672:15672"   # Web panel (http://localhost:15672)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
