// seedFoods.js
const mongoose = require("mongoose");
const dotenv = require("dotenv");
const Food = require("./models1/Food");

dotenv.config();

const foodDatabase = {
    // ... tüm yiyecekler burada
    "elma": { calories: 52 },
    "muz": { calories: 89 },
    "portakal": { calories: 47 },
    "üzüm": { calories: 69 },
    "çilek": { calories: 32 },
    "karpuz": { calories: 30 },
    "kavun": { calories: 34 },
    "şeftali": { calories: 39 },
    "armut": { calories: 57 },
    "kiraz": { calories: 50 },
    "vişne": { calories: 50 },
    "kayısı": { calories: 48 },
    "incir": { calories: 74 },
    "nar": { calories: 83 },
    "ananas": { calories: 50 },
    "avokado": { calories: 160 },
    "mango": { calories: 60 },
    "mandalina": { calories: 53 },
    "greyfurt": { calories: 42 },
    "limon": { calories: 29 },
    "havuç": { calories: 41 },
    "domates": { calories: 18 },
    "salatalık": { calories: 16 },
    "patates": { calories: 77 },
    "patates haşlama": { calories: 86 },
    "patates kızartma": { calories: 312 },
    "soğan": { calories: 40 },
    "sarımsak": { calories: 149 },
    "marul": { calories: 15 },
    "ıspanak": { calories: 23 },
    "brokoli": { calories: 34 },
    "karnabahar": { calories: 25 },
    "kabak": { calories: 17 },
    "patlıcan": { calories: 25 },
    "biber": { calories: 20 },
    "bezelye": { calories: 81 },
    "fasulye": { calories: 31 },
    "barbunya": { calories: 127 },
    "mercimek": { calories: 116 },
    "nohut": { calories: 164 },
    "bulgur": { calories: 342 },
    "pirinç": { calories: 130 },
    "pirinç pilavı": { calories: 205 },
    "makarna": { calories: 131 },
    "makarna haşlama": { calories: 158 },
    "mantı": { calories: 220 },
    "ekmek": { calories: 265 },
    "tam buğday ekmeği": { calories: 247 },
    "simit": { calories: 275 },
    "poğaça": { calories: 360 },
    "börek": { calories: 330 },
    "su böreği": { calories: 290 },
    "pide": { calories: 265 },
    "lahmacun": { calories: 330 },
    "pizza": { calories: 266 },
    "hamburger": { calories: 295 },
    "tavuk döner": { calories: 220 },
    "et döner": { calories: 280 }, "tavuk şiş": { calories: 180 },
    "tavuk kanat": { calories: 290 },
    "tavuk göğüs": { calories: 165 },
    "tavuk but": { calories: 209 },
    "balık": { calories: 206 },
    "somon": { calories: 208 },
    "ton balığı": { calories: 132 },
    "karides": { calories: 99 },
    "midye": { calories: 172 },
    "kalamar": { calories: 175 },
    "yumurta": { calories: 143 },
    "haşlanmış yumurta": { calories: 155 },
    "omlet": { calories: 154 },
    "menemen": { calories: 180 },
    "peynir": { calories: 402 },
    "beyaz peynir": { calories: 264 },
    "kaşar peyniri": { calories: 337 },
    "lor peyniri": { calories: 85 },
    "yoğurt": { calories: 59 },
    "süt": { calories: 42 },
    "ayran": { calories: 37 },
    "kefir": { calories: 41 },
    "dondurma": { calories: 207 },
    "kaymak": { calories: 793 },
    "tereyağı": { calories: 717 },
    "zeytinyağı": { calories: 884 },
    "ayçiçek yağı": { calories: 884 },
    "bal": { calories: 304 },
    "pekmez": { calories: 290 },
    "reçel": { calories: 278 },
    "fındık": { calories: 628 },
    "ceviz": { calories: 654 },
    "badem": { calories: 579 },
    "antep fıstığı": { calories: 562 },
    "kaju": { calories: 553 },
    "çekirdek": { calories: 584 },
    "leblebi": { calories: 477 },
    "bisküvi": { calories: 502 },
    "çikolata": { calories: 546 },
    "sütlü çikolata": { calories: 535 },
    "bitter çikolata": { calories: 598 },
    "gofret": { calories: 520 },
    "kek": { calories: 350 },
    "pasta": { calories: 350 },
    "baklava": { calories: 425 },
    "kadayıf": { calories: 330 },
    "lokum": { calories: 350 },
    "helva": { calories: 522 },
    "sütlaç": { calories: 140 },
    "kazandibi": { calories: 150 },
    "tavukgöğsü": { calories: 145 },
    "muhallebi": { calories: 120 },
    "kola": { calories: 42 },
    "meyve suyu": { calories: 45 },
    "limonata": { calories: 40 },
    "çay": { calories: 1 },
    "kahve": { calories: 2 },
    "sade kahve": { calories: 0 },
    "latte": { calories: 110 },
    "cappuccino": { calories: 120 },
    "nescafe": { calories: 70 },
    "türk kahvesi": { calories: 7 },
    "salep": { calories: 150 },
    "boza": { calories: 200 },
    "bira": { calories: 43 },
    "şarap": { calories: 83 },
    "rakı": { calories: 110 },
    "vodka": { calories: 231 },
    "viski": { calories: 250 },
    "su": { calories: 0 },
    "maden suyu": { calories: 0 },
    "tonik": { calories: 34 },
    "enerji içeceği": { calories: 45 },
    "kuru fasulye": { calories: 140 },
    "nohut yemeği": { calories: 168 },
    "mercimek çorbası": { calories: 90 },
    "ezogelin çorbası": { calories: 95 },
    "tarhana çorbası": { calories: 85 },
    "işkembe çorbası": { calories: 110 },
    "tavuk çorbası": { calories: 75 },
    "balık çorbası": { calories: 80 },
    "sebze çorbası": { calories: 70 },
    "domates çorbası": { calories: 65 },
    "mantar çorbası": { calories: 85 },
    "yoğurt çorbası": { calories: 90 },
    "pilav üstü kuru": { calories: 350 },
    "etli nohut": { calories: 220 },
    "karnıyarık": { calories: 280 },
    "imam bayıldı": { calories: 180 },
    "patlıcan musakka": { calories: 200 },
    "kabak mücver": { calories: 150 },
    "ıspanak yemeği": { calories: 120 },
    "pırasa yemeği": { calories: 110 },
    "taze fasulye": { calories: 90 },
    "bamya": { calories: 95 },
    "zeytinyağlı dolma": { calories: 130 },
    "etli dolma": { calories: 180 },
    "sarma": { calories: 160 },
    "mantı": { calories: 220 },
    "iskender": { calories: 450 },
    "adana kebap": { calories: 380 },
    "urfa kebap": { calories: 370 },
    "çiğ köfte": { calories: 180 },
    "lahmacun": { calories: 330 },
    "pide": { calories: 265 },
    "gözleme": { calories: 200 },
    "mantı": { calories: 220 },
    "menemen": { calories: 180 },
    "sucuklu yumurta": { calories: 250 },
    "pastırma": { calories: 250 },
    "sucuk": { calories: 452 },
    "salam": { calories: 340 },
    "sosis": { calories: 296 },
    "kavurma": { calories: 550 },
    "kokoreç": { calories: 330 },
    "midye dolma": { calories: 200 },
    "balık ekmek": { calories: 350 },
    "kumpir": { calories: 450 },
    "tost": { calories: 300 },
    "sandviç": { calories: 280 },
    "suşi": { calories: 200 },
    "ramen": { calories: 400 },
    "noodle": { calories: 190 },
    "waffle": { calories: 310 },
    "pankek": { calories: 227 },
    "granola": { calories: 471 },
    "müsli": { calories: 340 },
    "corn flakes": { calories: 357 },
    "yulaf ezmesi": { calories: 389 },
    "chia tohumu": { calories: 486 },
    "keten tohumu": { calories: 534 },
    "kinoa": { calories: 120 },
    "bulgur pilavı": { calories: 220 },
    "pirinç pilavı": { calories: 205 },
    "erişte": { calories: 360 },
    "şehriye çorbası": { calories: 85 }
    

};

const seedFoods = async () => {
    try {
        await mongoose.connect(process.env.MONGO_URL, {
            useNewUrlParser: true,
            useUnifiedTopology: true,
        });

        console.log("✅ MongoDB bağlantısı başarılı.");

        const operations = Object.entries(foodDatabase).map(async ([name, { calories }]) => {
            return Food.findOneAndUpdate(
                { name },
                { name, calories },
                { upsert: true, new: true }
            );
        });

        await Promise.all(operations);

        console.log("🍎 Besin verileri başarıyla yüklendi!");
        process.exit(0);
    } catch (err) {
        console.error("❌ Hata:", err);
        process.exit(1);
    }
};

seedFoods();